import { useState, MouseEvent } from "react";

import Head from "next/head";
import Link from "next/link";

import styles from "@/styles/Home.module.css";
import { ProgressBar } from "@/components/ProgressBar";

interface Props {
  title: string;
  data: {
    progressBars: {
      id: string;
      value: number;
    }[];
  };
}

export default function Home({
  title,
  data: { progressBars: defaultProgressBars },
}: Props) {
  const [progressBars, setProgressBars] = useState(defaultProgressBars);
  const [progressId, setProgressId] = useState("progress1");

  const handleButtonClick = (e: MouseEvent<HTMLButtonElement>) => {
    const target = e.target as HTMLButtonElement;

    const _progressBars = progressBars.map((progressBar) => {
      if (progressBar.id === progressId) {
        progressBar.value += parseInt(target.dataset.value || "0");
      }
      return progressBar;
    });
    setProgressBars(_progressBars);
  };

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <nav>
          <Link href="/about">About</Link>
        </nav>
        <div>
          <h1>{title}</h1>
          <div>
            {progressBars.map((progress) => (
              <ProgressBar
                key={progress.id}
                id={progress.id}
                value={progress.value}
              />
            ))}
          </div>

          <div>
            <select onChange={(e) => setProgressId(e.target.value)}>
              <option value="progress1">#progress1</option>
              <option value="progress2">#progress2</option>
              <option value="progress3">#progress3</option>
            </select>
            <button onClick={handleButtonClick} data-value="-25">
              -25
            </button>
            <button onClick={handleButtonClick} data-value="-10">
              -10
            </button>
            <button onClick={handleButtonClick} data-value="+10">
              +10
            </button>
            <button onClick={handleButtonClick} data-value="+25">
              +25
            </button>
          </div>
        </div>
      </main>
    </>
  );
}

// SSR
export async function getStaticProps() {
  return {
    props: {
      title: "Progress Bar Demo",
      data: {
        progressBars: [
          { id: "progress1", value: 0 },
          { id: "progress2", value: 0 },
          { id: "progress3", value: 0 },
        ],
      },
    },
  };
}
