import { useState, MouseEvent, useMemo } from "react";

import Head from "next/head";

import styles from "@/styles/Home.module.css";
import { ProgressBar } from "@/components/ProgressBar";
import { Button } from "@/components/Button";
import { Dropdown } from "@/components/Dropdown";

interface Props {
  title: string;
  data: {
    progressBars: {
      id: string;
      value: number;
    }[];
  };
}

export default function Home({
  title,
  data: { progressBars: defaultProgressBars },
}: Props) {
  const [progressBars, setProgressBars] = useState(defaultProgressBars);
  const [progressId, setProgressId] = useState("progress1");

  const dropdownOptions = useMemo(() => {
    return progressBars.map((progressBar) => progressBar.id);
  }, [progressBars]);

  const handleButtonClick = (e: MouseEvent<HTMLButtonElement>) => {
    const target = e.target as HTMLButtonElement;

    const _progressBars = progressBars.map((progressBar) => {
      if (progressBar.id === progressId) {
        progressBar.value += parseInt(target.dataset.value || "0");
        if (progressBar.value < 0) {
          progressBar.value = 0;
        }
      }
      return progressBar;
    });
    setProgressBars(_progressBars);
  };

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 style={{ marginBottom: "20px" }}>{title}</h1>
          <div style={{ marginBottom: "20px" }}>
            {progressBars.map((progress) => (
              <ProgressBar
                key={progress.id}
                id={progress.id}
                value={progress.value}
              />
            ))}
          </div>

          <div className={styles["control-wrapper"]}>
            <Dropdown
              onChange={(e) => setProgressId(e.target.value)}
              options={dropdownOptions}
            />
            <Button dataValue={"-25"} onClick={handleButtonClick}>
              -25
            </Button>
            <Button dataValue={"-10"} onClick={handleButtonClick}>
              -10
            </Button>

            <Button dataValue={"+10"} onClick={handleButtonClick}>
              +10
            </Button>
            <Button dataValue={"+25"} onClick={handleButtonClick}>
              +25
            </Button>
          </div>
        </div>
      </main>
    </>
  );
}

// SSR
export async function getStaticProps() {
  return {
    props: {
      title: "Progress Bar Demo",
      data: {
        progressBars: [
          { id: "progress1", value: 0 },
          { id: "progress2", value: 0 },
          { id: "progress3", value: 0 },
        ],
      },
    },
  };
}
